#include <raylib.h>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <stdbool.h>
#include <assert.h>
#include "const.c"
#include "global.c"
#include "util.c"
#include "fwd.c"
#include "ret.c"
#include "loss.c"
#include "grad.c"
#include "train.c"
#include "randomize.c"
#include "act.c"
#include "respond.c"
#include "plot.c"
#include "main.c"
